apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: foo
          value: bar
        - name: variable1
          valueFrom:
            configMapKeyRef:
              name: test-cm2
              key: var1
        - name: variable2
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: vraiable1
