apiVersion: v1
kind: PersistentVolume 
metadata:
 name: mysql-pv-volume
 namespace: demo 
 labels:
  type: local 
spec:
 storageClassName: manual 
 capacity:
  storage: 20Gi
 accessModes:
  - ReadWriteOnce  # Corregido: se añadió un espacio después del guion
 hostPath:
  path: "/mnt/data"

--- 
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
 name: mysql-pv-claim  # Corregido: se cambió 'clain' a 'claim'
 namespace: demo
spec:
 storageClassName: manual  # Añadido: debe coincidir con el PV
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 20Gi