apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-deployment
  name: mysql
  namespace: demo
spec:
  selector:
    matchLabels:
      app: mysql
  strategy: recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - image: msyql/mysql-driver
        name: mysql
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: password
        ports:
         - containerPort: 3306

        resources: 
         requests:
          cpu: "250m"
          memory: "64Mi"
         limits:
          cpu: "500m"
          memory: "1Gi"
        volumeMounts:
         - name: mysql-persistent-storage
           mountPath: /var/lib/mysql
         - name:
      volumes:
       - name: mysql-persistent-storage
         persistentVolumeClaim: 
          claimName: mysql-pv-claim
status: {}

---
apiVersion: v1
kind: Service
