name: Hola mundo 

on: [push, pull_request]

jobs:
  hola: 
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo 
        run: echo "Hola mundo"
      - name: touch file 
        run: touch hola.txt
      - name: Set text 
        run: echo "Hola mundo " >> hola.txt
      - name: Read file 
        run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: other mundo 
        run: ls -al
   
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4.2.2

      - name: ls 
        run: |
          echo "hola mundo" >> hola.txt
          cat hola.txt
          sudo apt-get install -y tree
          ls -al
      - name: ejecuta-script 
        run: |
          chmod +x script.sh

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: latest 

      - name: Version node
        run: node --version

      - name: php 
        uses: shivammathur/setup-php@v2
        with: 
          php-version: '8.3'
      
      - name: Version php 
        run: php --version

      - name: My action 
        uses: ./.github/actions/my-action
        with:
          message: "Manuonda"

  docker:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - name: Test
        run: ls -al      
  
  entorno:
    runs-on: ubuntu-latest
    env:
      MY_VAR: "Hola mundo environment"
    
    steps:
      - name: Test
        run: echo $MY_VAR
      - name: Test 2
        run: echo "Hola mundo ${MY_VAR}"
      - name: Test 3
        env:
          MY_VAR_2: "Hola mundo environment 2"
        run: echo $MY_VAR_2
  
  secrets_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Test vars environment
        run: echo ${{ vars.MY_VARIABLE_SPACE }}
      - name : Test secrets 
        run: echo ${{ secrets.MY_SECRET_SPACE }}