name: Hola mundo 

#on : [push, pull_request]
on :
 push:
   branches:  [main, pull_request]




jobs:
  hola: 
    runs-on: ubuntu-latest
    steps:
      - name : Hola mundo 
        run : echo "Hola mundo"
      - name : touch file 
        run : touch hola.txt
      - name : Set text 
        run : echo "Hola mundo " >> hola.txt
      - name: Read file 
        run : cat hola.txt


  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
     - name: Checkout
       uses: actions/checkout@v4.2.2
    -  name: other mundo 
       run : ls -al
   
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4.2.2

      - name: ls 
        run: |
          echo "hola mundo" >> hola.txt
          cat hola.txt
          apt-get install 
      - name : ejecuta-script 
        run: |
            chmod +x script.sh